### ISSUE TITLE
Game Crashes if Cards Are Selected in Quick Succession

### ISSUE THREAD

**Issue by ohara21** [chanlau/ExplodingKittens1.0#2]
Slightly different from the previous issue in that the game will crash even if you don't select the Trade 5 action. I selected one card in the discard pile, went back to my hand, and rapidly selected and deselected my cards until the game caught this exception:

E/AndroidRuntime: FATAL EXCEPTION: main
    Process: edu.up.cs301, PID: 24830
    java.lang.OutOfMemoryError: Failed to allocate a 61578012 byte allocation with 4186416 free bytes and 41MB until OOM
        at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
        at android.graphics.BitmapFactory.nativeDecodeAsset(Native Method)
        at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:655)
        at android.graphics.BitmapFactory.decodeResourceStream(BitmapFactory.java:483)
        at android.graphics.drawable.Drawable.createFromResourceStream(Drawable.java:1157)
        at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:720)
        at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java:571)
        at android.content.res.Resources.getDrawable(Resources.java:879)
        at android.content.Context.getDrawable(Context.java:530)
        at android.support.v4.content.ContextCompat.getDrawable(ContextCompat.java:358)
        at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:198)
        at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:186)
        at android.support.v7.content.res.AppCompatResources.getDrawable(AppCompatResources.java:100)
        at android.support.v7.widget.AppCompatImageHelper.setImageResource(AppCompatImageHelper.java:85)
        at android.support.v7.widget.AppCompatImageButton.setImageResource(AppCompatImageButton.java:84)
        at edu.up.cs301.ExplodingKittens.ExplodingKittensHumanPlayer.updateDisplay(ExplodingKittensHumanPlayer.java:442)
        at edu.up.cs301.ExplodingKittens.ExplodingKittensHumanPlayer.onClick(ExplodingKittensHumanPlayer.java:1257)
        at android.view.View.performClick(View.java:5675)
        at android.view.View$PerformClick.run(View.java:22651)
        at android.os.Handler.handleCallback(Handler.java:836)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:208)
        at android.app.ActivityThread.main(ActivityThread.java:6304)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)

**Comment by ohara21** [comment]
Nevermind, I just saw your comment on this known bug
